version: '3.4'
name: 'py-service-template'

services:
  services-api:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: ".env"
    ports:
      - "${EXTERNAL_SERVICES_API_PORT}:${SERVICES_API_PORT}"
    volumes:
      - ./src:/app/src
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:13
    env_file: ".env"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"