name: CD - Deploy to Railway

on:
  push:
    branches:
      - '**'

jobs:
  deploy: 
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set up Node.js (for Railway)
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install Railway CLI
      run: |
        npm install -g @railway/cli
    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        railway up

